apiVersion: v1
kind: Service
metadata:
  name: activator-service
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.activatorSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.activator.service.type }}
  selector:
    {{- include "knative-serving.selectorLabels" . | nindent 4 }}
    {{- include "knative-serving.activatorSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.activator.service.ports | toYaml | nindent 2 }}
