apiVersion: v1
kind: Secret
metadata:
  name: control-serving-certs
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: control-plane
  {{- include "knative-serving.labels" . | nindent 4 }}
