apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving.fullname" . }}-activator
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
  {{- include "knative-serving.activatorSelectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "knative-serving.selectorLabels" . | nindent 6 }}
    {{- include "knative-serving.activatorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "knative-serving.selectorLabels" . | nindent 8 }}
      {{- include "knative-serving.activatorSelectorLabels" . | nindent 8 }}
      {{- with .Values.activator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - env:
        - name: GOGC
          value: {{ quote .Values.activator.config.gogc }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ include "knative-serving.configLoggingName" . }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ include "knative-serving.configObservabilityName" . }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.global.config.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- with .Values.activator.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.activator.image.repository }}:{{ .Values.activator.image.tag | default .Chart.AppVersion }}{{- if .Values.activator.image.digest }}@{{ .Values.activator.image.digest }}{{- end }}
        imagePullPolicy: {{ .Values.activator.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 12
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: activator
            port: 8012
          initialDelaySeconds: 15
          periodSeconds: 10
        name: activator
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8012
          name: http1
        - containerPort: 8013
          name: h2c
        readinessProbe:
          failureThreshold: 5
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: activator
            port: 8012
          periodSeconds: 5
        resources: {{- toYaml .Values.activator.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.activator.containerSecurityContext | nindent 10 }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      serviceAccountName: {{ include "knative-serving.activatorServiceAccountName" . }}
      terminationGracePeriodSeconds: 600
      {{- with .Values.activator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.activator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.activator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.activator.topologySpreadConstraints }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
