apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator-cluster
  labels:
    serving.knative.dev/controller: "true"
  {{- include "knative-serving.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - revisions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator-cluster
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
  {{- include "knative-serving.activatorSelectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator-cluster
subjects:
- kind: ServiceAccount
  name: {{ include "knative-serving.activatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
