apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator
  labels:
    serving.knative.dev/controller: "true"
  {{- include "knative-serving.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - routing-serving-certs
  - knative-serving-certs
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
  {{- include "knative-serving.activatorSelectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "knative-serving.fullname" . }}-knative-serving-activator
subjects:
- kind: ServiceAccount
  name: {{ include "knative-serving.activatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
