apiVersion: v1
kind: Secret
metadata:
  name: routing-serving-certs
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane-routing
  {{- include "knative-serving.labels" . | nindent 4 }}
