apiVersion: v1
kind: Service
metadata:
  name: autoscaler
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.autoscalerSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.autoscaler.service.type }}
  selector:
    {{- include "knative-serving.selectorLabels" . | nindent 4 }}
    {{- include "knative-serving.autoscalerSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.autoscaler.service.ports | toYaml | nindent 2 }}
