{{- if .Values.autoscalerHpa.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving.fullname" . }}-autoscaler-hpa
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
  {{- include "knative-serving.autoscalerHpaSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscalerHpa.replicas }}
  selector:
    matchLabels:
    {{- include "knative-serving.selectorLabels" . | nindent 6 }}
    {{- include "knative-serving.autoscalerHpaSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "knative-serving.selectorLabels" . | nindent 8 }}
      {{- include "knative-serving.autoscalerHpaSelectorLabels" . | nindent 8 }}
      {{- with .Values.autoscalerHpa.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.global.config.configLoggingName }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.global.config.configObservabilityName }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.global.config.metricsDomain }}
        {{- with .Values.autoscalerHpa.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.autoscalerHpa.image.repository }}:{{ .Values.autoscalerHpa.image.tag | default .Chart.AppVersion }}{{- if .Values.autoscalerHpa.image.digest }}@{{ .Values.autoscalerHpa.image.digest }}{{- end }}
        imagePullPolicy: {{ .Values.autoscalerHpa.image.pullPolicy }}
        name: autoscaler-hpa
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8080
          name: probes
        livenessProbe:
            httpGet:
              path: /health
              port: probes
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: probes
            scheme: HTTP
          periodSeconds: 5
          failureThreshold: 5
        resources: {{- toYaml .Values.autoscalerHpa.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.autoscalerHpa.containerSecurityContext | nindent 10 }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      serviceAccountName: {{ include "knative-serving.controllerServiceAccountName" . }}
      {{- with .Values.autoscalerHpa.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscalerHpa.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscalerHpa.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscalerHpa.topologySpreadConstraints }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
