apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.controllerSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  selector:
    {{- include "knative-serving.selectorLabels" . | nindent 4 }}
    {{- include "knative-serving.controllerSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.controller.service.ports | toYaml | nindent 2 }}
