apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-serving.fullname" . }}-knative-serving-controller-admin
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.controllerSelectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-serving.fullname" . }}-knative-serving-admin
subjects:
- kind: ServiceAccount
  name: {{ include "knative-serving.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
