apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving.fullname" . }}-webhook
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
  {{- include "knative-serving.webookSelectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "knative-serving.selectorLabels" . | nindent 6 }}
    {{- include "knative-serving.webookSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "knative-serving.selectorLabels" . | nindent 8 }}
      {{- include "knative-serving.webookSelectorLabels" . | nindent 8 }}
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ include "knative-serving.configLoggingName" . }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ include "knative-serving.configObservabilityName" . }}
        - name: WEBHOOK_NAME
          value: webhook
        - name: WEBHOOK_PORT
          value: "8443"
        - name: METRICS_DOMAIN
          value: {{ quote .Values.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- with .Values.webhook.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}{{- if .Values.webhook.image.digest }}@{{ .Values.webhook.image.digest }}{{- end }}
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 1
        name: webhook
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8443
          name: https-webhook
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          periodSeconds: 1
        resources: {{- toYaml .Values.webhook.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.webhook.containerSecurityContext |
          nindent 10 }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      serviceAccountName: {{ include "knative-serving.controllerServiceAccountName" . }}
      terminationGracePeriodSeconds: 300
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.topologySpreadConstraints }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
