apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.webookSelectorLabels" . | nindent 4 }}
