{{- if .Values.webhook.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "knative-serving.fullname" . }}-webhook
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.webookSelectorLabels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.webhook.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webhook.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.webhook.autoscaling.targetCPUUtilizationPercentage }}
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.webhook.autoscaling.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
  {{- end }}
  {{- if .Values.webhook.autoscaling.targetMemoryUtilizationPercentage }}
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.webhook.autoscaling.targetMemoryUtilizationPercentage }}
        type: Utilization
    type: Resource
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "knative-serving.fullname" . }}-webhook
{{- end }}
