apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-serving.fullname" . }}-webhook
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.webookSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  selector:
    {{- include "knative-serving.selectorLabels" . | nindent 4 }}
    {{- include "knative-serving.webookSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.service.ports | toYaml | nindent 2 }}
