{{- if .Values.configFeatures.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.controllerSelectorLabels" . | nindent 4 }}
{{- with .Values.configFeatures.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
