{{- if .Values.configTracing.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  labels:
    app.kubernetes.io/component: tracing
    {{- include "knative-serving.labels" . | nindent 4 }}
{{- with .Values.configTracing.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
