{{- if .Values.configLogging.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving.configLoggingName" . }}
  labels:
    app.kubernetes.io/component: logging
    {{- include "knative-serving.labels" . | nindent 4 }}
{{- with .Values.configLogging.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
