{{- if .Values.configLogging.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.config.configLoggingName }}
  labels:
    app.kubernetes.io/component: logging
    {{- include "knative-serving.labels" . | nindent 4 }}
data:
  {{- $example := pick .Values.configLogging.data "_example" -}}
  {{- $sanitized := omit .Values.configLogging.data "_example" -}}
  {{- toYaml $example | nindent 2 }}
  {{- if $sanitized }}
  {{- tpl (toYaml $sanitized) . | nindent 2 }}
  {{- end }}
{{- end }}
