{{- if .Values.configFeatures.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
    {{- include "knative-serving.controllerSelectorLabels" . | nindent 4 }}
data:
  {{- $example := pick .Values.configFeatures.data "_example" -}}
  {{- $sanitized := omit .Values.configFeatures.data "_example" -}}
  {{- toYaml $example | nindent 2 }}
  {{- if $sanitized }}
  {{- tpl (toYaml $sanitized) . | nindent 2 }}
  {{- end }}
{{- end }}
