{{- if .Values.configNetwork.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  labels:
    app.kubernetes.io/component: networking
  {{- include "knative-serving.labels" . | nindent 4 }}
data:
  {{- $example := pick .Values.configNetwork.data "_example" -}}
  {{- $sanitized := omit .Values.configNetwork.data "_example" -}}
  {{- toYaml $example | nindent 2 }}
  {{- if index .Values "net-istio" "enabled" }}
  ingress-class: "istio.ingress.networking.knative.dev"
  {{- $sanitized := omit $sanitized "ingress-class" -}}
  {{- if $sanitized }}
  {{- tpl (toYaml $sanitized) . | nindent 2 }}
  {{- end }}
  {{- else }}
  {{- if $sanitized }}
  {{- tpl (toYaml $sanitized) . | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
