apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  name: queue-proxy
  labels:
    app.kubernetes.io/component: queue-proxy
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  image: {{ .Values.queueProxy.image.repository }}:{{ .Values.queueProxy.image.tag | default .Chart.AppVersion }}{{- if .Values.queueProxy.image.digest }}@{{ .Values.queueProxy.image.digest }}{{- end }}
